version: '3.8'
services:
  # Giữ lại các DB nội bộ để làm fallback
  postgres-db:
    image: postgres:16-alpine
    container_name: crs-main-postgres-db
    environment:
      POSTGRES_DB: crs_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:7-alpine
    container_name: crs-main-redis

  backend-app:
    build: ./services/backend-app
    container_name: crs-main-backend-app
    restart: unless-stopped
    dns:
      - 8.8.8.8
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_OPTIONS=--dns-result-order=ipv4first
      # DÒNG QUAN TRỌNG NHẤT ĐỂ CHẠY ĐƯỢC TRÊN CLOUD:
      - NODE_TLS_REJECT_UNAUTHORIZED=0

  kong:
    image: kong:3.4
    container_name: crs-main-kong
    dns:
      - 8.8.8.8
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_LISTEN: 0.0.0.0:8000
    volumes:
      - ./kong:/usr/local/kong/declarative
    ports:
      - "8000:8000"
    depends_on:
      - backend-app

  frontend:
    build: ./services/frontend
    container_name: crs-main-frontend
    dns:
      - 8.8.8.8
    ports:
      - "5173:5173"
    depends_on:
      - kong

volumes:
  postgres-data: